[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA redirect so router works on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Global security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Allow only your own origin to use camera & geolocation.
    # Keeping mic disabled (adjust to (self) if you ever add voice features).
    Permissions-Policy = "geolocation=(self), camera=(self), microphone=()"

# Make sure the manifest serves with the correct type
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# Let the SW update immediately instead of being cached forever by proxies
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

